import { test } from "node:test";
import assert from "node:assert/strict";
import { diffLockfileTexts, parseLockfile } from "../src/lockfile/index.js";
import { detectYarnFlavor } from "../src/lockfile/yarn.js";
import { managerByName } from "../src/testrun/index.js";

const manifest = { dependencies: { a: "^1.0.0", "@s/scoped": "^2.0.0", alias: "npm:real@^1.0.0" }, devDependencies: { d: "^1" } };

const reg = (n: string, v: string) => `  resolved "https://registry.yarnpkg.com/${n}/-/${n}-${v}.tgz#abc"`;
const classic = (a: string, extra = "") => `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@s/scoped@^2.0.0":
  version "2.0.0"
${reg("@s/scoped", "2.0.0")}

a@^1.0.0, a@~1.0.0:
  version "${a}"
${reg("a", a)}
  dependencies:
    t "^1.0.0"

t@^1.0.0:
  version "1.0.0"
${reg("t", "1.0.0")}
${extra}`;

const berry = (a: string, extra = "") => `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10c0

"@s/scoped@npm:^2.0.0":
  version: 2.0.0
  resolution: "@s/scoped@npm:2.0.0"
  checksum: 1
  languageName: node
  linkType: hard

"a@npm:^1.0.0, a@npm:~1.0.0":
  version: ${a}
  resolution: "a@npm:${a}"
  dependencies:
    t: "npm:^1.0.0"
  languageName: node
  linkType: hard

"t@npm:^1.0.0":
  version: 1.0.0
  resolution: "t@npm:1.0.0"
  languageName: node
  linkType: hard

"app@workspace:.":
  version: 0.0.0-use.local
  resolution: "app@workspace:."
  languageName: unknown
  linkType: soft
${extra}`;

test("flavor detection", () => {
  assert.equal(detectYarnFlavor(classic("1.0.0")), "classic");
  assert.equal(detectYarnFlavor(berry("1.0.0")), "berry");
});

for (const [flavor, make] of [["classic", classic], ["berry", berry]] as const) {
  test(`${flavor}: parses scoped names, multiple ranges per entry, skips workspaces`, () => {
    const pkgs = parseLockfile(make("1.0.0"));
    assert.deepEqual([...pkgs.keys()].sort(), ["node_modules/@s/scoped", "node_modules/a", "node_modules/t"]);
    assert.equal(pkgs.get("node_modules/a")?.version, "1.0.0");
  });

  test(`${flavor}: bump of a direct dep and transitive-only bump`, () => {
    const bump = make("1.1.0");
    const changes = diffLockfileTexts(make("1.0.0"), bump, manifest);
    assert.deepEqual(changes, [{ name: "a", path: "node_modules/a", kind: "changed", oldVersion: "1.0.0", newVersion: "1.1.0", direct: true }]);
  });

  test(`${flavor}: identical lockfiles give no changes`, () => {
    assert.deepEqual(diffLockfileTexts(make("1.0.0"), make("1.0.0"), manifest), []);
  });
}

test("classic: added and removed entries, transitive flagged", () => {
  const extra = `\nnew-dep@^1:\n  version "1.0.0"\n${reg("new-dep", "1.0.0")}\n`;
  const changes = diffLockfileTexts(classic("1.0.0"), classic("1.0.0", extra), manifest);
  assert.deepEqual(changes.map((c) => [c.name, c.kind, c.direct]), [["new-dep", "added", false]]);
  const removed = diffLockfileTexts(classic("1.0.0", extra), classic("1.0.0"), manifest);
  assert.deepEqual(removed.map((c) => [c.name, c.kind]), [["new-dep", "removed"]]);
});

test("berry: transitive-only bump", () => {
  const next = berry("1.0.0").replace('version: 1.0.0\n  resolution: "t@npm:1.0.0"', 'version: 1.0.1\n  resolution: "t@npm:1.0.1"');
  const changes = diffLockfileTexts(berry("1.0.0"), next, manifest);
  assert.deepEqual(changes.map((c) => [c.name, c.oldVersion, c.newVersion, c.direct]), [["t", "1.0.0", "1.0.1", false]]);
});

test("classic: npm: alias installs the real package, direct via the alias name", () => {
  const lock = `# yarn lockfile v1\n\n\nalias@npm:real@^1.0.0:\n  version "1.2.0"\n${reg("real", "1.2.0")}\n`;
  const pkgs = parseLockfile(lock);
  assert.deepEqual([...pkgs.values()], [{ name: "real", version: "1.2.0", aliases: ["alias"] }]);
  const next = lock.replace(/1\.2\.0/g, "1.3.0");
  assert.deepEqual(diffLockfileTexts(lock, next, manifest).map((c) => [c.name, c.direct]), [["real", true]]);
});

test("berry: npm: alias resolves to the real name; patch and git resolutions are skipped", () => {
  const lock = `__metadata:\n  version: 8\n\n"alias@npm:real@^1.0.0":\n  version: 1.2.0\n  resolution: "real@npm:1.2.0"\n\n"real@patch:real@npm%3A1.2.0#./p.patch::version=1.2.0&hash=1":\n  version: 1.2.0\n  resolution: "real@patch:real@npm%3A1.2.0#./p.patch::version=1.2.0&hash=1"\n\n"g@github:x/g#commit=abc":\n  version: 1.0.0\n  resolution: "g@https://github.com/x/g.git#commit=abc"\n`;
  const pkgs = parseLockfile(lock);
  assert.deepEqual([...pkgs.entries()], [["node_modules/real", { name: "real", version: "1.2.0", aliases: ["alias"] }]]);
});

test("classic: git, file and non-registry entries are skipped", () => {
  const lock = `# yarn lockfile v1\n\n\n"g@github:x/g":\n  version "1.0.0"\n  resolved "https://codeload.github.com/x/g/tar.gz/abc"\n\nf@file:../f:\n  version "1.0.0"\n\nok@^1:\n  version "1.0.0"\n${reg("ok", "1.0.0")}\n`;
  assert.deepEqual([...parseLockfile(lock).keys()], ["node_modules/ok"]);
});

test("several versions of one name: keyed per range so a bump still lines up", () => {
  const two = (v: string) => `# yarn lockfile v1\n\n\nx@^1.0.0:\n  version "${v}"\n${reg("x", v)}\n\nx@^2.0.0:\n  version "2.0.0"\n${reg("x", "2.0.0")}\n`;
  assert.deepEqual([...parseLockfile(two("1.0.0")).keys()].sort(), ["node_modules/x@^1.0.0", "node_modules/x@^2.0.0"]);
  const changes = diffLockfileTexts(two("1.0.0"), two("1.1.0"), { dependencies: { x: "^1" } });
  assert.deepEqual(changes.map((c) => [c.name, c.oldVersion, c.newVersion, c.direct]), [["x", "1.0.0", "1.1.0", true]]);
});

test("non-matches: descriptor-only text, empty file, comments only", () => {
  assert.equal(parseLockfile("# yarn lockfile v1\n\n").size, 0);
  assert.equal(parseLockfile("").size, 0);
  assert.equal(parseLockfile("a@^1:\n  dependencies:\n    b \"^1\"\n").size, 0);
});

test("manager specs: frozen install and single-dependency pin per flavor", () => {
  const yarn = managerByName("yarn");
  assert.deepEqual(yarn.frozenInstall(classic("1.0.0")), ["install", "--frozen-lockfile"]);
  assert.deepEqual(yarn.frozenInstall(berry("1.0.0")), ["install", "--immutable"]);
  assert.deepEqual(yarn.pinDependency("a", "1.2.3", classic("1.0.0")), ["add", "a@1.2.3", "--ignore-scripts"]);
  assert.deepEqual(yarn.pinDependency("a", "1.2.3", berry("1.0.0")), ["add", "a@1.2.3", "--mode=skip-build"]);
  assert.deepEqual(managerByName("npm").frozenInstall(""), ["ci"]);
});
