name: ci
on: [push, pull_request]
jobs:
  test-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with: { node-version: 24 }
      - run: npm ci
      - run: npm run lint
      - run: npm test
  test:
    name: test
    needs: test-matrix
    runs-on: ubuntu-latest
    steps:
      - run: true
